name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do codigo
      uses: actions/checkout@v4

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "20.x"
        cache: npm
        cache-dependency-path: api/package.json

    - name: Instalar dependencias
      working-directory: api
      run: npm install --no-package-lock

    - name: Executar testes
      working-directory: api
      run: npm test

